# Dependencies
markdown:      kramdown
highlighter:   rouge

# Permalinks
permalink:        pretty

# Exclude present folder since we'll make HTMLs ourself
exclude:          ['present/tips/*.md']

# Setup
title:            Nicolas Deffense
description:      'Scientific Reasearcher at <a href="https://uclouvain.be/en/index.html">UCLouvain</a>'
tagline:          'Remote sensing, Python, science'
url:              https://nicolasdeffense.github.io/
baseurl:          /
author:
  name:           Nicolas Deffense
  url:            https://nicolasdeffense.github.io/

paginate:         5
paginate_path: "posts/page:num"


disqus_shortname: ceholden

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/nicolasdeffense/nicolasdeffense.github.io

gems:
  - jekyll-mentions
  - github-pages


theme: jekyll-theme-cayman